config/routes.rb
Rails.application.routes.draw do

  resources :product_leads
  resources :newsletters, :only => [:show, :create]
  # post '/tinymce_assets' => 'tinymce_assets#create'
  resources :products, :only => [:index, :show]
  resources :contacts, :only => [:new, :show, :create]
  resources :contact_leads
  resources :find_its, :only => [:new, :show, :create]
  resources :homes, :only => [:index]

  # ADMIN
  namespace :admin do
    resources :product_leads
    resources :budgets
    resources :contact_leads
    resources :colors
    resources :users
    resources :contacts
    resources :products do
      resources :product_informations
      resources :product_highlights
      resources :product_images
    end
    resources :newsletters
    resources :highlights
    resources :find_its
    resources :system_configurations do
      member do
        get :not_commercial_catalog
        get :not_technical_guide
      end
    end
    root :to => 'statics#index'
  end
  #/ADMIN

  resource :user_session, only: [:create, :new, :destroy]

  root to: 'homes#index'

  match 'register', to: "users#new", via: :all
  match 'login', to: 'user_sessions#new', via: :all
  match 'logout', to: 'user_sessions#destroy', via: :all

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/budget.rb
class Budget < ActiveRecord::Base
  belongs_to :product
end

app/models/color.rb
class Color < ActiveRecord::Base
  has_and_belongs_to_many :products, dependent: :destroy

  def color_name
    "#{color} - #{name}"
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/contact_lead.rb
class ContactLead < ActiveRecord::Base
end

app/models/find_it.rb
class FindIt < ActiveRecord::Base
end

app/models/highlight.rb
class Highlight < ActiveRecord::Base

  has_attached_file :image_highlight, styles: {
                      :thumb => "93x93#"
                    }
  validates_attachment :image_highlight, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base

  has_many :product_informations
  has_many :product_highlights
  has_many :product_images
  has_and_belongs_to_many :colors

  has_attached_file :product_image,:styles => {:small => "100x100#", :large => "500x500>"}
  has_attached_file :display_picture,:styles => {:small => "100x100#", :large => "500x500>"}
  has_attached_file :image_entry,:styles => {:small => "100x100#", :large => "200x400#"}
  has_attached_file :sketchup

  validates_attachment_content_type :product_image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates_attachment_content_type :display_picture, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates_attachment_content_type :image_entry, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates_attachment_file_name :sketchup, matches: [/skp\z/]

  def url_slug()
    "#{id}-#{title.parameterize}"
  end

end

app/models/product_highlight.rb
class ProductHighlight < ActiveRecord::Base
  belongs_to :product
  has_attached_file :highlight_product, styles: {
                      :thumb => "93x93#"
                    }
  validates_attachment_content_type :highlight_product, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  def url_slug()
    "#{product_id}-#{product.title.parameterize}"
  end

end

app/models/product_image.rb
class ProductImage < ActiveRecord::Base
  belongs_to :product
  has_attached_file :image_product, styles: {
                      :medium => "350x400#",
                      :thumb => "93x93#"
                    }
  validates_attachment_content_type :image_product, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  def url_slug()
    "#{product_id}-#{product.title.parameterize}"
  end
end

app/models/product_lead.rb
class ProductLead < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
  acts_as_authorization_role join_table_name: :roles_users

  def role_params
      params.require(:role).permit(:name, :authorizable_type, :authorizable_id)
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor :role

  acts_as_authentic do |c|
    c.login_field = "login"
  end


  acts_as_authorization_subject :association_name => :roles, :join_table_name => :roles_users
  after_save :define_role

  def role
    @role
    if self.has_role? :administrator
      @role = :administrator
    elsif self.has_role? :supervisor
      @role = :supervisor
    else self.has_role? :user
      @role = :user
    end
  end

  def define_role
    if @role
      self.has_no_roles!
      self.has_role! @role
    end
  end

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  single_access_allowed_request_types :any

  def to_key
    new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
end

app/controllers/admin/find_its_controller.rb
class Admin::FindItsController < ApplicationController
  before_action :set_find_it, only: [:show, :edit, :update, :destroy]
  layout "admin"

  # GET /find_its
  # GET /find_its.json
  def index
    @find_its = FindIt.all
  end

  # GET /find_its/1
  # GET /find_its/1.json
  def show
  end

  # GET /find_its/new
  def new
    @find_it = FindIt.new
  end

  # GET /find_its/1/edit
  def edit
  end

  # POST /find_its
  # POST /find_its.json
  def create
    @find_it = FindIt.new(find_it_params)

    respond_to do |format|
      if @find_it.save
        format.html { redirect_to @find_it, notice: 'Find it was successfully created.' }
        format.json { render :show, status: :created, location: @find_it }
      else
        format.html { render :new }
        format.json { render json: @find_it.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /find_its/1
  # PATCH/PUT /find_its/1.json
  def update
    respond_to do |format|
      if @find_it.update(find_it_params)
        format.html { redirect_to @find_it, notice: 'Find it was successfully updated.' }
        format.json { render :show, status: :ok, location: @find_it }
      else
        format.html { render :edit }
        format.json { render json: @find_it.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /find_its/1
  # DELETE /find_its/1.json
  def destroy
    @find_it.destroy
    respond_to do |format|
      format.html { redirect_to find_its_url, notice: 'Find it was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_find_it
      @find_it = FindIt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def find_it_params
      params.require(:find_it).permit(:name, :email, :phone, :city, :state, :published, :active)
    end
end

app/controllers/find_its_controller.rb
class FindItsController < ApplicationController
  before_filter :load_application

  def new
    @find_it = FindIt.new
  end

  def create
    @find_it = FindIt.new(find_it_params)
    if @find_it.save
      Notifier.send_findIt(@find_it).deliver
      Notifier.send_findIt_user(@find_it).deliver
    else
      @erro = true
    end

  end

  def show
  end

  private
    def find_it_params
      params.require(:find_it).permit!
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_boolean(value)
    if value
      return "Sim"
    else
      return "Não"
    end
  end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/find_its_helper.rb
module FindItsHelper
end

app/helpers/highlights_helper.rb
module HighlightsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/find_its/_form.html.haml
= form_for @find_it do |f|
  - if @find_it.errors.any?
    #error_explanation
      %h2= "#{pluralize(@find_it.errors.count, "error")} prohibited this find_it from being saved:"
      %ul
        - @find_it.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :phone
    = f.text_field :phone
  .field
    = f.label :city
    = f.text_field :city
  .field
    = f.label :state
    = f.text_field :state
  .field
    = f.label :published
    = f.text_field :published
  .field
    = f.label :active
    = f.text_field :active
  .actions
    = f.submit 'Save'

app/views/admin/find_its/edit.html.haml
%h1 Editing find_it

= render 'form'

= link_to 'Show', @find_it
\|
= link_to 'Back', find_its_path

app/views/admin/find_its/index.html.haml
%ol.breadcrumb.a
  %li=link_to "Home", "javascript:void(0);"
  %li.active=link_to "Onde Encontrar", "javascript:void(0);"

.row
  .col-xs-12
    %h1 Onde Encontrar
  / .col-xs-3
  /   =link_to "+ Contato", new_contact_path, :class => "btn btn-default pull-right header-button"

.col-xs-12.search
  %form
    .col-xs-11
      %label.sr-only
        Busca
      %input.form-control.input-form{:name => "search"}
    .col-xs-1
      %input.btn.btn-default{:type => "submit", :value => "Buscar"}
  .clearfix

.col-xs-12.ordering-box
  .btn-group
    %a.btn.btn-white{:href => "contacts"} Todos
    %a.btn.btn-white{:href => "?filter=#"} #
    %a.btn.btn-white{:href => "?filter=a"} A
    %a.btn.btn-white{:href => "?filter=b"} B
    %a.btn.btn-white{:href => "?filter=c"} C
    %a.btn.btn-white{:href => "?filter=d"} D
    %a.btn.btn-white{:href => "?filter=e"} E
    %a.btn.btn-white{:href => "?filter=f"} F
    %a.btn.btn-white{:href => "?filter=g"} G
    %a.btn.btn-white{:href => "?filter=h"} H
    %a.btn.btn-white{:href => "?filter=i"} I
    %a.btn.btn-white{:href => "?filter=j"} J
    %a.btn.btn-white{:href => "?filter=k"} K
    %a.btn.btn-white{:href => "?filter=l"} L
    %a.btn.btn-white{:href => "?filter=m"} M
    %a.btn.btn-white{:href => "?filter=n"} N
    %a.btn.btn-white{:href => "?filter=o"} O
    %a.btn.btn-white{:href => "?filter=p"} P
    %a.btn.btn-white{:href => "?filter=q"} Q
    %a.btn.btn-white{:href => "?filter=r"} R
    %a.btn.btn-white{:href => "?filter=s"} S
    %a.btn.btn-white{:href => "?filter=t"} T
    %a.btn.btn-white{:href => "?filter=u"} U
    %a.btn.btn-white{:href => "?filter=v"} V
    %a.btn.btn-white{:href => "?filter=w"} W
    %a.btn.btn-white{:href => "?filter=x"} X
    %a.btn.btn-white{:href => "?filter=y"} Y
    %a.btn.btn-white{:href => "?filter=z"} Z

.users
  %table.col-xs-12.table.table-condensed
    %tr
      %th Nome
      %th E-mail
      %th Telefone
      %th Estado
      %th Cidade
      %th
    - for find_it in @find_its
      %tr
        %td= find_it.name
        %td= find_it.email
        %td= find_it.phone
        %td= find_it.state
        %td= find_it.city
        %td
          =link_to t("show"), admin_find_it_path(find_it), :class => "btn btn-white"

app/views/admin/find_its/new.html.haml
%h1 New find_it

= render 'form'

= link_to 'Back', find_its_path

app/views/admin/find_its/show.html.haml
%ol.breadcrumb
  %li=link_to "Home", root_path
  %li.active=link_to "Onde Encontrar", admin_find_its_path

.row
  .col-xs-12
    %h1 Onde Encontrar

.comunicados
  %h3 Nome
  %h2.details= @find_it.name

  %h3 Email
  %h2.details=@find_it.email

  %h3 Telefone
  %h2.details=@find_it.phone

  %h3 Cidade
  %h2.details=@find_it.city

  %h3 Estado
  %h2.details=@find_it.state

  %h3 Enviado em
  %h2.details=@find_it.created_at.strftime("%d/%m/%y")
%br
= link_to 'Exibir Todos', admin_find_its_path, :class => "btn btn-white"