config/routes.rb
Rails.application.routes.draw do

  resources :product_leads
  resources :newsletters, :only => [:show, :create]
  # post '/tinymce_assets' => 'tinymce_assets#create'
  resources :products, :only => [:index, :show]
  resources :contacts, :only => [:new, :show, :create]
  resources :contact_leads
  resources :find_its, :only => [:new, :show, :create]
  resources :homes, :only => [:index]

  # ADMIN
  namespace :admin do
    resources :product_leads
    resources :budgets
    resources :contact_leads
    resources :colors
    resources :users
    resources :contacts
    resources :products do
      resources :product_informations
      resources :product_highlights
      resources :product_images
    end
    resources :newsletters
    resources :highlights
    resources :find_its
    resources :system_configurations do
      member do
        get :not_commercial_catalog
        get :not_technical_guide
      end
    end
    root :to => 'statics#index'
  end
  #/ADMIN

  resource :user_session, only: [:create, :new, :destroy]

  root to: 'homes#index'

  match 'register', to: "users#new", via: :all
  match 'login', to: 'user_sessions#new', via: :all
  match 'logout', to: 'user_sessions#destroy', via: :all

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/budget.rb
class Budget < ActiveRecord::Base
  belongs_to :product
end

app/models/color.rb
class Color < ActiveRecord::Base
  has_and_belongs_to_many :products, dependent: :destroy

  def color_name
    "#{color} - #{name}"
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/contact_lead.rb
class ContactLead < ActiveRecord::Base
end

app/models/find_it.rb
class FindIt < ActiveRecord::Base
end

app/models/highlight.rb
class Highlight < ActiveRecord::Base

  has_attached_file :image_highlight, styles: {
                      :thumb => "93x93#"
                    }
  validates_attachment :image_highlight, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base

  has_many :product_informations
  has_many :product_highlights
  has_many :product_images
  has_and_belongs_to_many :colors

  has_attached_file :product_image,:styles => {:small => "100x100#", :large => "500x500>"}
  has_attached_file :display_picture,:styles => {:small => "100x100#", :large => "500x500>"}
  has_attached_file :image_entry,:styles => {:small => "100x100#", :large => "200x400#"}
  has_attached_file :sketchup

  validates_attachment_content_type :product_image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates_attachment_content_type :display_picture, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates_attachment_content_type :image_entry, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates_attachment_file_name :sketchup, matches: [/skp\z/]

  def url_slug()
    "#{id}-#{title.parameterize}"
  end

end

app/models/product_highlight.rb
class ProductHighlight < ActiveRecord::Base
  belongs_to :product
  has_attached_file :highlight_product, styles: {
                      :thumb => "93x93#"
                    }
  validates_attachment_content_type :highlight_product, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  def url_slug()
    "#{product_id}-#{product.title.parameterize}"
  end

end

app/models/product_image.rb
class ProductImage < ActiveRecord::Base
  belongs_to :product
  has_attached_file :image_product, styles: {
                      :medium => "350x400#",
                      :thumb => "93x93#"
                    }
  validates_attachment_content_type :image_product, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  def url_slug()
    "#{product_id}-#{product.title.parameterize}"
  end
end

app/models/product_lead.rb
class ProductLead < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
  acts_as_authorization_role join_table_name: :roles_users

  def role_params
      params.require(:role).permit(:name, :authorizable_type, :authorizable_id)
  end

end

app/models/system_configuration.rb
class SystemConfiguration < ActiveRecord::Base

  has_attached_file :commercial_catalog
  has_attached_file :technical_guide

  has_attached_file :institutional_image,:styles => {:small => "100x100#", :home => "348x400>"}

  validates_attachment_content_type :institutional_image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  validates_attachment_content_type :commercial_catalog, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif", 'application/pdf', 'application/msword', 'text/plain']

  validates_attachment_content_type :technical_guide, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif", 'application/pdf', 'application/msword', 'text/plain']

end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor :role

  acts_as_authentic do |c|
    c.login_field = "login"
  end


  acts_as_authorization_subject :association_name => :roles, :join_table_name => :roles_users
  after_save :define_role

  def role
    @role
    if self.has_role? :administrator
      @role = :administrator
    elsif self.has_role? :supervisor
      @role = :supervisor
    else self.has_role? :user
      @role = :user
    end
  end

  def define_role
    if @role
      self.has_no_roles!
      self.has_role! @role
    end
  end

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  single_access_allowed_request_types :any

  def to_key
    new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
end

app/controllers/admin/system_configurations_controller.rb
class Admin::SystemConfigurationsController < ApplicationController
  # before_action :set_system_configuration, only: [:show, :edit, :update, :destroy]
  layout "admin"
  # GET /system_configurations
  # GET /system_configurations.json
  def index
    redirect_to admin_system_configuration_path(1)
  end

  # GET /system_configurations/1
  # GET /system_configurations/1.json
  def show
    @system_configuration = SystemConfiguration.find(1)
  end

  # GET /system_configurations/new
  def new
    redirect_to admin_system_configuration_path(1)
  end

  # GET /system_configurations/1/edit
  def edit
    @system_configuration = SystemConfiguration.find(1)
  end

  # POST /system_configurations
  # POST /system_configurations.json
  def create
    redirect_to admin_system_configuration_path(1)
  end

  # PATCH/PUT /system_configurations/1
  # PATCH/PUT /system_configurations/1.json
  def update
    @system_configuration = SystemConfiguration.find(1)
    respond_to do |format|
      if @system_configuration.update(system_configuration_params)
        format.html { redirect_to [:admin, @system_configuration], notice: 'System configuration was successfully updated.' }
        format.json { render :show, status: :ok, location: [:admin, @system_configuration] }
      else
        format.html { render :edit }
        format.json { render json: @system_configuration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /system_configurations/1
  # DELETE /system_configurations/1.json
  def destroy
    redirect_to admin_system_configuration_path(1)
  end

  def not_commercial_catalog
    @system_configuration = SystemConfiguration.find(1)
    @system_configuration.commercial_catalog = nil
    @system_configuration.save
    redirect_to admin_system_configuration_path(1)
  end

  def not_technical_guide
    @system_configuration = SystemConfiguration.find(1)
    @system_configuration.technical_guide = nil
    @system_configuration.save
    redirect_to admin_system_configuration_path(1)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_system_configuration
      @system_configuration = SystemConfiguration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def system_configuration_params
      params.require(:system_configuration).permit!
    end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/find_its_helper.rb
module FindItsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/system_configurations_helper.rb
module SystemConfigurationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/system_configurations/_form.html.haml
.row
  .col-sm-12.top-space.a
    = form_for [:admin, @system_configuration], role: "form" do |f|
      - if @system_configuration.errors.any?
        #error_explanation
          %h2= "#{pluralize(@system_configuration.errors.count, "error")} prohibited this system_configuration from being saved:"
          %ul
            - @system_configuration.errors.full_messages.each do |message|
              %li= message

      %p
        %small *Caso nenhum endereço seja informado o item na será exibido no site
        = f.text_field :restricted_area_link, :class => "form-control", placeholder: "Endereço do Acesso Restrito"
      %p
        %small *Caso nenhum endereço seja informado o item na será exibido no site
        = f.text_field :facebook_link, :class => "form-control", placeholder: "Endereço do Facebook"
      %p
        %small *Caso nenhum endereço seja informado o item na será exibido no site
        = f.text_field :link_instagram, :class => "form-control", placeholder: "Endereço do Instagram"
      %p
        %small *Caso nenhum endereço seja informado o item na será exibido no site
        = f.text_field :link_pinterest, :class => "form-control", placeholder: "Endereço do Pinterest"
      %p
        = f.text_field :institutional_title, :class => "form-control", placeholder: "Titulo do Texto Institucional"
      %p
        = f.trix_editor :institutional_text, :class => "form-control", placeholder: "Texto Institucional"
      %p
        %small Imagem Institucional
        = f.file_field :institutional_image, :class => "form-control"
      - if @system_configuration.institutional_image.file?
        .form-group
          =image_tag(@system_configuration.institutional_image.url)
      %p
        %label Emails para o enviar no Formulário de Contato
        %small.d-block *Utilize a ","(virgula) ou tab para adicionar mais de um item
        = f.text_field :senders_contact, :class => "form-control tagsinput", placeholder: "Emails para o enviar no Formulário de Contato"
      %p
        %label Emails para o enviar no Formulário do Onde Encotrar
        %small.d-block *Utilize a ","(virgula) ou tab para adicionar mais de um item
        = f.text_field :senders_where_to_find, :class => "form-control tagsinput", placeholder: "Emails para o enviar no Formulário do Onde Encotrar"
      %p
        %small Catalogo Comercial
        = f.file_field :commercial_catalog, :class => "form-control"
      - if @system_configuration.commercial_catalog.file?
        %p
          =link_to(@system_configuration.commercial_catalog.instance_read(:file_name),@system_configuration.commercial_catalog.url, :target => "_blank")
          =link_to("Excluir Catalogo Comercial", not_commercial_catalog_admin_system_configuration_path("Lytos"),data: { :confirm => "Essa operação não pode ser cancelada, todas as alterações que não foram atualizadas serão perdidas!\n\tDeseja prosseguir?"}, :class=>"btn btn-default" )
      %p
        %small Guia Técnico
        = f.file_field :technical_guide, :class => "form-control"
      - if @system_configuration.technical_guide.file?
        %p
          =link_to( @system_configuration.technical_guide.instance_read(:file_name),@system_configuration.technical_guide.url, :target => "_blank")
          =link_to("Excluir Guia Tecnico", not_technical_guide_admin_system_configuration_path("Lytos"),data: {:confirm => "Essa operação não pode ser cancelada, todas as alterações que não foram atualizadas serão perdidas!\n\tDeseja prosseguir?"}, :class=>"btn btn-default" )

      .actions
        = f.submit 'Salvar', :class => "btn btn-default pull-right"

app/views/admin/system_configurations/edit.html.haml
%h1 Editing system_configuration

= render 'form'

app/views/admin/system_configurations/index.html.haml
%h1 Listing system_configurations

%table
  %thead
    %tr
      %th Restricted area link
      %th Facebook link
      %th Link instagram
      %th Link pinterest
      %th Institutional title
      %th Institutional text
      %th Senders contact
      %th Senders where to find
      %th Commercial catalog file name
      %th Commercial catalog content type
      %th Commercial catalog file size
      %th Commercial catalog updated at
      %th Technical guide file name
      %th Technical guide content type
      %th Technical guide file size
      %th Technical guide updated at
      %th Institutional image file name
      %th Institutional image content type
      %th Institutional image file size
      %th Institutional image updated at
      %th
      %th
      %th

  %tbody
    - @system_configurations.each do |system_configuration|
      %tr
        %td= system_configuration.restricted_area_link
        %td= system_configuration.facebook_link
        %td= system_configuration.link_instagram
        %td= system_configuration.link_pinterest
        %td= system_configuration.institutional_title
        %td= system_configuration.institutional_text
        %td= system_configuration.senders_contact
        %td= system_configuration.senders_where_to_find
        %td= system_configuration.commercial_catalog_file_name
        %td= system_configuration.commercial_catalog_content_type
        %td= system_configuration.commercial_catalog_file_size
        %td= system_configuration.commercial_catalog_updated_at
        %td= system_configuration.technical_guide_file_name
        %td= system_configuration.technical_guide_content_type
        %td= system_configuration.technical_guide_file_size
        %td= system_configuration.technical_guide_updated_at
        %td= system_configuration.institutional_image_file_name
        %td= system_configuration.institutional_image_content_type
        %td= system_configuration.institutional_image_file_size
        %td= system_configuration.institutional_image_updated_at
        %td= link_to 'Show', system_configuration
        %td= link_to 'Edit', edit_system_configuration_path(system_configuration)
        %td= link_to 'Destroy', system_configuration, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New System configuration', new_system_configuration_path

app/views/admin/system_configurations/new.html.haml
%h1 New system_configuration

= render 'form'

= link_to 'Back', system_configurations_path

app/views/admin/system_configurations/show.html.haml
%ol.breadcrumb
  %li=link_to "Home", admin_root_path
  %li.active=link_to "Configuração do Sistema", ''

.row
  .col-xs-9
    %h1 Configurações do Sistema Lythos
  .col-xs-3
    =link_to "Editar", edit_admin_system_configuration_path, :class => "btn btn-default pull-right header-button"

- if flash[:notice]
  .alert.alert-success
    %b Concluído!
    Registro modificado com
    %b sucesso!

.comunicados
  %h3 Endereço do Acesso Restrito:
  %h2.details= @system_configuration.restricted_area_link

  %h3 Endereço do Facebook
  %h2.details=@system_configuration.facebook_link

  %h3 Endereço do Instagram
  %h2.details=@system_configuration.link_instagram

  %h3 Endereço do Pinterest
  %h2.details=@system_configuration.link_pinterest

  %h3 Titulo do Texto Institucional
  %h2.details=@system_configuration.institutional_title

  %h3 Texto Institucional:
  %h2.details=raw @system_configuration.institutional_text

  - if @system_configuration.institutional_image.file?
    %h3 Imagem Institucional:
    =image_tag(@system_configuration.institutional_image.url)

  %h3 Emails para o enviar no Formulário de Contato:
  %h2.details=@system_configuration.senders_contact

  %h3 Emails para o enviar no Formulário do Onde Encotrar:
  %h2.details=@system_configuration.senders_where_to_find

  - if @system_configuration.commercial_catalog.file?
    %h3 Catalogo Comercial:
    %p
    %strong=link_to( @system_configuration.commercial_catalog.instance_read(:file_name),@system_configuration.commercial_catalog.url, :target => "_blank")
  %p
  - if @system_configuration.technical_guide.file?
    %h3 Guia Técnico:
    %p
    %strong=link_to( @system_configuration.technical_guide.instance_read(:file_name),@system_configuration.technical_guide.url, :target => "_blank")