config/routes.rb
Rails.application.routes.draw do

  resources :product_leads
  resources :newsletters, :only => [:show, :create]
  # post '/tinymce_assets' => 'tinymce_assets#create'
  resources :products, :only => [:index, :show]
  resources :contacts, :only => [:new, :show, :create]
  resources :contact_leads
  resources :find_its, :only => [:new, :show, :create]
  resources :homes, :only => [:index]

  # ADMIN
  namespace :admin do
    resources :product_leads
    resources :budgets
    resources :contact_leads
    resources :colors
    resources :users
    resources :contacts
    resources :products do
      resources :product_informations
      resources :product_highlights
      resources :product_images
    end
    resources :newsletters
    resources :highlights
    resources :find_its
    resources :system_configurations do
      member do
        get :not_commercial_catalog
        get :not_technical_guide
      end
    end
    root :to => 'statics#index'
  end
  #/ADMIN

  resource :user_session, only: [:create, :new, :destroy]

  root to: 'homes#index'

  match 'register', to: "users#new", via: :all
  match 'login', to: 'user_sessions#new', via: :all
  match 'logout', to: 'user_sessions#destroy', via: :all

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/budget.rb
class Budget < ActiveRecord::Base
  belongs_to :product
end

app/models/color.rb
class Color < ActiveRecord::Base
  has_and_belongs_to_many :products, dependent: :destroy

  def color_name
    "#{color} - #{name}"
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/contact_lead.rb
class ContactLead < ActiveRecord::Base
end

app/models/find_it.rb
class FindIt < ActiveRecord::Base
end

app/models/highlight.rb
class Highlight < ActiveRecord::Base

  has_attached_file :image_highlight, styles: {
                      :thumb => "93x93#"
                    }
  validates_attachment :image_highlight, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base

  has_many :product_informations
  has_many :product_highlights
  has_many :product_images
  has_and_belongs_to_many :colors

  has_attached_file :product_image,:styles => {:small => "100x100#", :large => "500x500>"}
  has_attached_file :display_picture,:styles => {:small => "100x100#", :large => "500x500>"}
  has_attached_file :image_entry,:styles => {:small => "100x100#", :large => "200x400#"}
  has_attached_file :sketchup

  validates_attachment_content_type :product_image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates_attachment_content_type :display_picture, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates_attachment_content_type :image_entry, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates_attachment_file_name :sketchup, matches: [/skp\z/]

  def url_slug()
    "#{id}-#{title.parameterize}"
  end

end

app/models/product_highlight.rb
class ProductHighlight < ActiveRecord::Base
  belongs_to :product
  has_attached_file :highlight_product, styles: {
                      :thumb => "93x93#"
                    }
  validates_attachment_content_type :highlight_product, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  def url_slug()
    "#{product_id}-#{product.title.parameterize}"
  end

end

app/models/product_image.rb
class ProductImage < ActiveRecord::Base
  belongs_to :product
  has_attached_file :image_product, styles: {
                      :medium => "350x400#",
                      :thumb => "93x93#"
                    }
  validates_attachment_content_type :image_product, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  def url_slug()
    "#{product_id}-#{product.title.parameterize}"
  end
end

app/models/product_information.rb
class ProductInformation < ActiveRecord::Base
end

app/models/product_lead.rb
class ProductLead < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
  acts_as_authorization_role join_table_name: :roles_users

  def role_params
      params.require(:role).permit(:name, :authorizable_type, :authorizable_id)
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor :role

  acts_as_authentic do |c|
    c.login_field = "login"
  end


  acts_as_authorization_subject :association_name => :roles, :join_table_name => :roles_users
  after_save :define_role

  def role
    @role
    if self.has_role? :administrator
      @role = :administrator
    elsif self.has_role? :supervisor
      @role = :supervisor
    else self.has_role? :user
      @role = :user
    end
  end

  def define_role
    if @role
      self.has_no_roles!
      self.has_role! @role
    end
  end

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  single_access_allowed_request_types :any

  def to_key
    new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
end

app/controllers/admin/product_informations_controller.rb
class Admin::ProductInformationsController < ApplicationController
  before_action :set_product_information, only: [:show, :edit, :update, :destroy]
  before_action :load_product

  layout "admin"
  # GET /product_informations
  # GET /product_informations.json
  def index
    @product_informations = ProductInformation.all
  end

  # GET /product_informations/1
  # GET /product_informations/1.json
  def show
  end

  # GET /product_informations/new
  def new
    @product_information = ProductInformation.new
  end

  # GET /product_informations/1/edit
  def edit
  end

  # POST /product_informations
  # POST /product_informations.json
  def create
    @product_information = ProductInformation.new(product_information_params)

    respond_to do |format|
      if @product_information.save
        format.html { redirect_to [:admin, @product, @product_information], notice: 'Product information was successfully created.' }
        format.json { render :show, status: :created, location: @product_information }
      else
        format.html { render :new }
        format.json { render json: [:admin, @product, @product_information.errors], status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_informations/1
  # PATCH/PUT /product_informations/1.json
  def update
    respond_to do |format|
      if @product_information.update(product_information_params)
        format.html { redirect_to [:admin, @product, @product_information], notice: 'Product information was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_information }
      else
        format.html { render :edit }
        format.json { render json: [:admin, @product, @product_information.errors], status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_informations/1
  # DELETE /product_informations/1.json
  def destroy
    @product_information.destroy
    respond_to do |format|
      format.html { redirect_to admin_product_product_informations_url, notice: 'Product information was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def load_product
      @product = Product.find(params[:product_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_product_information
      @product_information = ProductInformation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_information_params
      params.require(:product_information).permit(:attribute_title, :value, :active, :published, :produt_id)
    end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/find_its_helper.rb
module FindItsHelper
end

app/helpers/product_informations_helper.rb
module ProductInformationsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/product_informations/_form.html.haml
.row
  .col-sm-12.top-space.a
    = form_for [:admin, @product, @product_information], role: "form" do |f|
      / = f.error_messages
      %p
        = f.text_field :attribute_title, :class => "form-control", :placeholder => "Titulo"
      %p
        = f.text_field :value, :class => "form-control", :placeholder => "Informação"
      %p
        = f.check_box :published, :class=>"switch-large", :"data-text-label"=>"Exibir"

      =f.submit "Salvar", :class => "btn btn-default pull-right"

app/views/admin/product_informations/edit.html.haml
%ol.breadcrumb
  %li=link_to "Home", "javascript:void(0);"
  %li=link_to "Produtos", admin_products_path
  %li=link_to "Informações Técnicas", admin_product_product_informations_path

.row
  .col-xs-9
    %h1 Editar Informação Técnicas

- if flash[:error]
  .alert.alert-danger
    %b Ops!
    Está faltando alguma coisa

= render :partial => "form"

%br
= link_to 'Exibir Todos', admin_product_product_informations_path, :class => "btn btn-white"

app/views/admin/product_informations/index.html.haml
%ol.breadcrumb
  %li=link_to "Home", "/admin"
  %li.active=link_to "Produtos", admin_products_path
  %li.active=link_to "Informações Técnicas", admin_product_product_informations_path

.row
  .col-xs-9
    %h1 Informações Técnicas
  .col-xs-3
    =link_to "+ Informação Técnica", new_admin_product_product_information_path, :class => "btn btn-default pull-right header-button"

- if flash[:notice]
  .alert.alert-success
    %b Concluído!
    Registro modificado com
    %b sucesso!

/ .col-xs-12.search
/   %form
/     .col-xs-11
/       %label.sr-only
/         Busca
/       %input.form-control.input-form{:name => "search"}
/     .col-xs-1
/       %input.btn.btn-default{:type => "submit", :value => "Buscar"}
/   .clearfix

.users
  %table.col-xs-12.table.table-condensed
    %thead
      %tr
        %th Titulo
        %th Informação
        %th Publicado?
        %th Ações
    %tbody
      - for product_information in @product_informations
        %tr
          %td= product_information.attribute_title
          %td= product_information.value
          %td
            =link_to t("show"), admin_product_product_information_path(@product, product_information), :class => "btn btn-white"
            =link_to t("edit"), edit_admin_product_product_information_path(@product, product_information), :class => "btn btn-white"
            =link_to "Excluir", [:admin, @product, product_information], data: { :confirm => 'Are you sure?'}, :method => :delete, :class => "btn btn-default"

app/views/admin/product_informations/new.html.haml
%ol.breadcrumb
  %li=link_to "Home", "javascript:void(0);"
  %li=link_to "Produtos", admin_products_path
  %li=link_to "Informações Técnicas", admin_product_product_informations_path

.row
  .col-xs-9
    %h1 Nova Informação Técnica

- if flash[:error]
  .alert.alert-danger
    %b Ops!
    Está faltando alguma coisa

= render :partial => "form"

= link_to 'Exibir Todos', admin_product_product_informations_path, :class => "btn btn-white"

app/views/admin/product_informations/show.html.haml
%ol.breadcrumb
  %li=link_to "Home", admin_root_path
  %li.active=link_to "Produtos", admin_products_path
  %li.active=link_to "Informações Técnicas", admin_product_product_informations_path

.row
  .col-xs-9
    %h1 Produtos
  .col-xs-3
    =link_to "+ Informação Técnica", new_admin_product_product_information_path, :class => "btn btn-default pull-right header-button"

- if flash[:notice]
  .alert.alert-success
    %b Concluído!
    Registro modificado com
    %b sucesso!

.comunicados
  %h3 Titulo
  %h2.details= @product_information.attribute_title

  %h3 Informação
  %h2.details=@product_information.value

  %h3 Publicado?
  %h2.details= show_boolean(@product_information.published)
%br
= link_to 'Exibir Todos', admin_product_product_informations_path, :class => "btn btn-white"