config/routes.rb
Rails.application.routes.draw do

  resources :product_leads
  resources :newsletters, :only => [:show, :create]
  # post '/tinymce_assets' => 'tinymce_assets#create'
  resources :products, :only => [:index, :show]
  resources :contacts, :only => [:new, :show, :create]
  resources :contact_leads
  resources :find_its, :only => [:new, :show, :create]
  resources :homes, :only => [:index]

  # ADMIN
  namespace :admin do
    resources :product_leads
    resources :budgets
    resources :contact_leads
    resources :colors
    resources :users
    resources :contacts
    resources :products do
      resources :product_informations
      resources :product_highlights
      resources :product_images
    end
    resources :newsletters
    resources :highlights
    resources :find_its
    resources :system_configurations do
      member do
        get :not_commercial_catalog
        get :not_technical_guide
      end
    end
    root :to => 'statics#index'
  end
  #/ADMIN

  resource :user_session, only: [:create, :new, :destroy]

  root to: 'homes#index'

  match 'register', to: "users#new", via: :all
  match 'login', to: 'user_sessions#new', via: :all
  match 'logout', to: 'user_sessions#destroy', via: :all

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/budget.rb
class Budget < ActiveRecord::Base
  belongs_to :product
end

app/models/color.rb
class Color < ActiveRecord::Base
  has_and_belongs_to_many :products, dependent: :destroy

  def color_name
    "#{color} - #{name}"
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/contact_lead.rb
class ContactLead < ActiveRecord::Base
end

app/models/find_it.rb
class FindIt < ActiveRecord::Base
end

app/models/highlight.rb
class Highlight < ActiveRecord::Base

  has_attached_file :image_highlight, styles: {
                      :thumb => "93x93#"
                    }
  validates_attachment :image_highlight, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base

  has_many :product_informations
  has_many :product_highlights
  has_many :product_images
  has_and_belongs_to_many :colors

  has_attached_file :product_image,:styles => {:small => "100x100#", :large => "500x500>"}
  has_attached_file :display_picture,:styles => {:small => "100x100#", :large => "500x500>"}
  has_attached_file :image_entry,:styles => {:small => "100x100#", :large => "200x400#"}
  has_attached_file :sketchup

  validates_attachment_content_type :product_image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates_attachment_content_type :display_picture, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates_attachment_content_type :image_entry, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates_attachment_file_name :sketchup, matches: [/skp\z/]

  def url_slug()
    "#{id}-#{title.parameterize}"
  end

end

app/models/product_highlight.rb
class ProductHighlight < ActiveRecord::Base
  belongs_to :product
  has_attached_file :highlight_product, styles: {
                      :thumb => "93x93#"
                    }
  validates_attachment_content_type :highlight_product, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  def url_slug()
    "#{product_id}-#{product.title.parameterize}"
  end

end

app/models/product_image.rb
class ProductImage < ActiveRecord::Base
  belongs_to :product
  has_attached_file :image_product, styles: {
                      :medium => "350x400#",
                      :thumb => "93x93#"
                    }
  validates_attachment_content_type :image_product, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  def url_slug()
    "#{product_id}-#{product.title.parameterize}"
  end
end

app/models/product_lead.rb
class ProductLead < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
  acts_as_authorization_role join_table_name: :roles_users

  def role_params
      params.require(:role).permit(:name, :authorizable_type, :authorizable_id)
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor :role

  acts_as_authentic do |c|
    c.login_field = "login"
  end


  acts_as_authorization_subject :association_name => :roles, :join_table_name => :roles_users
  after_save :define_role

  def role
    @role
    if self.has_role? :administrator
      @role = :administrator
    elsif self.has_role? :supervisor
      @role = :supervisor
    else self.has_role? :user
      @role = :user
    end
  end

  def define_role
    if @role
      self.has_no_roles!
      self.has_role! @role
    end
  end

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  single_access_allowed_request_types :any

  def to_key
    new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
end

app/controllers/admin/highlights_controller.rb
class Admin::HighlightsController < ApplicationController
  before_action :set_highlight, only: [:show, :edit, :update, :destroy]
  layout "admin"

  # GET /highlights
  # GET /highlights.json
  def index
    @highlights = Highlight.all
  end

  # GET /highlights/1
  # GET /highlights/1.json
  def show
  end

  # GET /highlights/new
  def new
    @highlight = Highlight.new
  end

  # GET /highlights/1/edit
  def edit
  end

  # POST /highlights
  # POST /highlights.json
  def create
    @highlight = Highlight.new(highlight_params)

    respond_to do |format|
      if @highlight.save
        format.html { redirect_to [:admin, @highlight], notice: 'Highlight was successfully created.' }
        format.json { render :show, status: :created, location: @highlight }
      else
        format.html { render :new }
        format.json { render json: @highlight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /highlights/1
  # PATCH/PUT /highlights/1.json
  def update
    respond_to do |format|
      if @highlight.update(highlight_params)
        format.html { redirect_to [:admin, @highlight], notice: 'Highlight was successfully updated.' }
        format.json { render :show, status: :ok, location: @highlight }
      else
        format.html { render :edit }
        format.json { render json: @highlight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /highlights/1
  # DELETE /highlights/1.json
  def destroy
    @highlight.destroy
    respond_to do |format|
      format.html { redirect_to admin_highlights_url, notice: 'Highlight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_highlight
      @highlight = Highlight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def highlight_params
      params.require(:highlight).permit!
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_boolean(value)
    if value
      return "Sim"
    else
      return "Não"
    end
  end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/find_its_helper.rb
module FindItsHelper
end

app/helpers/highlights_helper.rb
module HighlightsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/highlights/_form.html.haml
.row
  .col-sm-12.top-space.a
    = form_for [:admin, @highlight], role: "form" do |f|
      / = f.error_messages
      %p
        = f.text_field :title, :class => "form-control", :placeholder => "Titulo"
      %p
        = f.text_field :subtitle, :class => "form-control", :placeholder => "Subtitulo"
      %p.datetimepicker.input-group.date
        %span.input-group-addon.btn-default
          %i.fa.fa-calendar
        = f.text_field :publication_start, :class => "form-control", :placeholder => "Inicio da Publicação"

      %p.datetimepicker.input-group.date
        %span.input-group-addon.btn-default
          %i.fa.fa-calendar
        = f.text_field :publication_stop, :class => "form-control", :placeholder => "Fim da Publicação"
      %p
        = f.number_field :order, :class => "form-control"
      %p
        = f.file_field :image_highlight, :class => "form-control filestyle"
      - if @highlight.image_highlight.file?
        .form-group
          =image_tag(@highlight.image_highlight.url)
      %p
        = f.text_field :link, :class => "form-control", :placeholder => "Link"
      %br
      .row
        .colorSelector.col-sm-2
          = f.label "Cor 1"
          %div{:style => "background-color: ##{@highlight.color1}; "}
          = f.hidden_field :color1, :value=>@highlight.color1, :class=>"hidden-color"
        .colorSelector.col-sm-2
          = f.label "Cor 2"
          %div{:style => "background-color: ##{@highlight.color2}; "}
          = f.hidden_field :color2, :value=>@highlight.color2, :class=>"hidden-color"
        .colorSelector.col-sm-2
          = f.label "Cor 3"
          %div{:style => "background-color: ##{@highlight.color3}; "}
          = f.hidden_field :color3, :value=>@highlight.color3, :class=>"hidden-color"
        .colorSelector.col-sm-2
          = f.label "Cor 4"
          %div{:style => "background-color: ##{@highlight.color4}; "}
          = f.hidden_field :color4, :value=>@highlight.color4, :class=>"hidden-color"


      =f.submit "Salvar", :class => "btn btn-default pull-right"

app/views/admin/highlights/edit.html.haml
%ol.breadcrumb
  %li=link_to "Home", "javascript:void(0);"
  %li=link_to "Destaques", "javascript:void(0);"

.row
  .col-xs-9
    %h1 Editar Destaque

- if flash[:error]
  .alert.alert-danger
    %b Ops!
    Está faltando alguma coisa

= render :partial => "form"

%br
= link_to 'Exibir Todos', admin_highlights_path, :class => "btn btn-white"

app/views/admin/highlights/index.html.haml
%ol.breadcrumb
  %li=link_to "Home", "/admin"
  %li.active=link_to "Destaques", admin_highlights_path

.row
  .col-xs-9
    %h1 Destaques
  .col-xs-3
    =link_to "+ Destaque", new_admin_highlight_path, :class => "btn btn-default pull-right header-button"

- if flash[:notice]
  .alert.alert-success
    %b Concluído!
    Registro modificado com
    %b sucesso!

.users
  %table.col-xs-12.table.table-condensed
    %thead
      %tr
        %th= "Thumb"
        %th="Titulo"
        %th="Inicio"
        %th="Fim"
        %th="Publicado?"
        %th="Ações"
    %tbody
      - for highlight in @highlights
        %tr
          - if highlight.image_highlight.file?
            %td= image_tag(highlight.image_highlight.url(:thumb))
          %td= highlight.title
          %td= highlight.publication_start.strftime("%d/%m/%y - %H:%M")
          %td= highlight.publication_stop.strftime("%d/%m/%y - %H:%M")
          %td= show_boolean(highlight.published)
          %td
            =link_to t("show"), admin_highlight_path(highlight), :class => "btn btn-white"
            =link_to t("edit"), edit_admin_highlight_path(highlight), :class => "btn btn-white"
            =link_to "Excluir", [:admin, highlight], data: { :confirm => 'Are you sure?'}, :method => :delete, :class => "btn btn-default"

app/views/admin/highlights/new.html.haml
%ol.breadcrumb
  %li=link_to "Home", "javascript:void(0);"
  %li=link_to "Destaques", "javascript:void(0);"

.row
  .col-xs-9
    %h1 Novo Destaque

- if flash[:error]
  .alert.alert-danger
    %b Ops!
    Está faltando alguma coisa

= render :partial => "form"

= link_to 'Exibir Todos', admin_highlights_path, :class => "btn btn-white"

app/views/admin/highlights/show.html.haml
%ol.breadcrumb
  %li=link_to "Home", root_path
  %li.active=link_to "Destaques", admin_highlights_path

.row
  .col-xs-9
    %h1 Destaques
  .col-xs-3
    =link_to "+ Destaque", new_admin_highlight_path, :class => "btn btn-default pull-right header-button"

- if flash[:notice]
  .alert.alert-success
    %b Concluído!
    Registro modificado com
    %b sucesso!

.comunicados
  %h3 Destaque
  %h2.details= @highlight.title

  %h3 Subtitulo
  %h2.details=@highlight.subtitle

  %h3 Inicia em
  %h2.details=@highlight.publication_start.strftime("%d/%m/%y - %H:%M")

  %h3 Termina em
  %h2.details=@highlight.publication_stop.strftime("%d/%m/%y - %H:%M")

  %h3 ordem
  %h2.details=@highlight.order

  %h3 link
  %h2.details=@highlight.link.present? ? @highlight.link : "Sem Link"

  %h3 Publicado?
  %h2.details=show_boolean(@highlight.published)

  - if @highlight.image_highlight.file?
    .box-body
      %p=image_tag(@highlight.image_highlight.url, style: "width: 50%;")

%br
= link_to 'Editar', edit_admin_highlight_path(@highlight), :class => "btn btn-white"